import {Platform, StyleSheet} from 'react-native';

const C = {
  blue: '#075EAA',
  blueDark: '#06477F',
  green: '#18834B',
  greenSoft: '#E8F4EC',
  ink: '#183247',
  muted: '#667B8C',
  line: '#D7E1E9',
  paper: '#FFFFFF',
  background: '#EEF3F7',
  paleBlue: '#EAF2F8',
  amber: '#A86A00',
  amberSoft: '#FFF5DB',
  red: '#B83B42',
  redSoft: '#FFF0F0',
};

const styles = StyleSheet.create({
  flex: {flex: 1},
  appRoot: {flex: 1, backgroundColor: C.background},
  authRoot: {flex: 1, backgroundColor: C.background},
  authScroll: {flexGrow: 1, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 28},
  authBrandRow: {flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 18, paddingVertical: 16, marginHorizontal: -18, marginTop: -18, marginBottom: 16, backgroundColor: C.blue, borderBottomColor: C.green, borderBottomWidth: 3},
  brandName: {color: C.paper, fontSize: 20, fontWeight: '800', letterSpacing: 0.2},
  brandSub: {color: '#E5F0F7', fontSize: 10, marginTop: 2},
  brandMark: {width: 40, height: 40, borderRadius: 14, backgroundColor: C.greenSoft, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#C8E7D1'},
  brandMarkLarge: {width: 54, height: 54, borderRadius: 18},
  brandMarkText: {fontSize: 23, fontWeight: '900', color: C.green, marginTop: -2},
  brandLeaf: {position: 'absolute', width: 8, height: 5, backgroundColor: '#7BC34B', borderRadius: 8, transform: [{rotate: '-28deg'}], right: 8, top: 9},
  authCard: {backgroundColor: C.paper, borderColor: C.line, borderWidth: 1, borderRadius: 12, padding: 18, shadowColor: '#183247', shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: {width: 0, height: 5}, elevation: 2},
  eyebrow: {alignSelf: 'flex-start', backgroundColor: C.paleBlue, borderRadius: 7, paddingHorizontal: 9, paddingVertical: 5, marginBottom: 10},
  eyebrowText: {color: C.blue, fontSize: 10, fontWeight: '800', letterSpacing: 0.8},
  authTitle: {fontSize: 26, lineHeight: 33, fontWeight: '800', color: C.ink},
  authSub: {color: C.muted, fontSize: 14, lineHeight: 21, marginTop: 7, marginBottom: 16},
  authFooter: {alignItems: 'center', paddingTop: 22, gap: 6},
  authFooterText: {fontSize: 12, color: C.muted, fontWeight: '700'},
  authFooterSub: {fontSize: 11, color: '#8A97AB', textAlign: 'center'},
  appHeader: {minHeight: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, paddingVertical: 8, backgroundColor: C.blue, borderBottomColor: C.green, borderBottomWidth: 3},
  headerBrand: {flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1, marginRight: 6},
  headerBrandCopy: {flex: 1},
  headerBrandName: {fontSize: 14, fontWeight: '800', color: C.paper, letterSpacing: 0.2},
  headerBrandSub: {fontSize: 8, color: '#E5F0F7', marginTop: 2},
  headerAccount: {flexDirection: 'row', alignItems: 'center', gap: 6, maxWidth: 145},
  headerOnlineDot: {width: 7, height: 7, borderRadius: 4},
  headerAccountText: {fontSize: 11, fontWeight: '700', color: C.paper, maxWidth: 76},
  headerAvatar: {overflow: 'hidden', textAlign: 'center', textAlignVertical: 'center', width: 31, height: 31, backgroundColor: C.paper, borderRadius: 16, fontSize: 13, fontWeight: '800', color: C.blue},
  offlineBanner: {minHeight: 34, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: C.amberSoft, paddingHorizontal: 12, paddingVertical: 6},
  serverBanner: {backgroundColor: C.paleBlue},
  offlineIcon: {color: C.amber, fontSize: 16, fontWeight: '800'},
  offlineBannerText: {fontSize: 11, color: C.amber, fontWeight: '700'},
  monitoringBanner: {minHeight: 25, paddingHorizontal: 12, paddingVertical: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#DDF5E6'},
  monitoringBannerText: {fontSize: 9, color: '#276844', fontWeight: '700', textAlign: 'center'},
  noticeWrap: {paddingHorizontal: 16, paddingTop: 7},
  dismissText: {textAlign: 'right', color: C.muted, fontSize: 10, marginTop: -4, marginBottom: 3},
  screenContent: {paddingHorizontal: 14, paddingTop: 13, paddingBottom: 12},
  bottomSpacer: {height: 6},
  pageIntro: {marginBottom: 13, padding: 12, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderLeftWidth: 4, borderLeftColor: C.green, borderRadius: 9},
  pageIntroRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  historyActions: {alignItems: 'flex-end', gap: 9, paddingVertical: 3},
  pageEyebrow: {fontSize: 9, letterSpacing: 0.7, color: C.blue, fontWeight: '800', marginBottom: 4},
  pageTitle: {fontSize: 22, lineHeight: 28, fontWeight: '800', color: C.ink},
  pageSub: {color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 5},
  welcomeBlock: {padding: 14, marginBottom: 11, backgroundColor: C.paper, borderColor: C.line, borderWidth: 1, borderLeftWidth: 4, borderLeftColor: C.green, borderRadius: 9},
  welcomeEyebrow: {fontSize: 10, color: C.green, fontWeight: '800', letterSpacing: 1},
  welcomeTitle: {fontSize: 25, lineHeight: 32, color: C.ink, fontWeight: '800', marginTop: 5},
  welcomeSub: {fontSize: 13, color: C.muted, marginTop: 4},
  summaryGrid: {flexDirection: 'row', gap: 9, marginBottom: 12},
  summaryCard: {flex: 1, minHeight: 104, padding: 10, borderRadius: 10, backgroundColor: C.paper, borderColor: C.line, borderWidth: 1},
  summaryIcon: {width: 29, height: 29, borderRadius: 9, justifyContent: 'center', alignItems: 'center'},
  summaryIconText: {fontSize: 17, fontWeight: '800'},
  summaryValue: {fontSize: 17, fontWeight: '800', color: C.ink, marginTop: 8},
  summaryLabel: {fontSize: 10, color: C.muted, marginTop: 1},
  card: {backgroundColor: C.paper, borderRadius: 10, borderColor: C.line, borderWidth: 1, padding: 13, marginBottom: 10},
  statusCard: {padding: 15},
  statusHead: {flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 5},
  statusDot: {width: 8, height: 8, borderRadius: 4},
  statusTitle: {fontSize: 14, fontWeight: '800', color: C.ink, flex: 1},
  cardTitle: {fontSize: 16, color: C.ink, fontWeight: '800'},
  cardTitleRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8},
  cardSub: {fontSize: 12, color: C.muted, lineHeight: 18, marginTop: 4, marginBottom: 10},
  bodyText: {fontSize: 13, color: '#46546B', lineHeight: 20, marginTop: 7},
  sectionHeading: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6, marginBottom: 9},
  sectionTitle: {fontSize: 16, fontWeight: '800', color: C.ink},
  sectionHint: {fontSize: 11, color: C.muted},
  quickGrid: {gap: 8, marginBottom: 12},
  quickAction: {minHeight: 53, borderRadius: 9, backgroundColor: C.paper, borderColor: C.line, borderWidth: 1, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 10},
  quickIcon: {width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center'},
  quickIconText: {fontSize: 19, fontWeight: '800'},
  quickLabel: {fontSize: 13, color: C.ink, fontWeight: '700', flex: 1},
  quickArrow: {fontSize: 22, color: '#98A5B8'},
  button: {minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 7, paddingHorizontal: 14, backgroundColor: C.green, marginTop: 10},
  buttonLight: {backgroundColor: C.paper, borderColor: '#B8C9D7', borderWidth: 1},
  buttonBlue: {backgroundColor: C.blue},
  buttonDanger: {backgroundColor: C.redSoft, borderColor: '#F0CED0', borderWidth: 1},
  buttonDisabled: {opacity: 0.48},
  buttonText: {color: C.paper, fontSize: 14, fontWeight: '800', textAlign: 'center'},
  buttonLightText: {color: C.blue},
  buttonDangerText: {color: C.red},
  buttonSpinner: {marginRight: 8},
  buttonRow: {flexDirection: 'row', gap: 8},
  dashboardSearch: {minHeight: 43, paddingHorizontal: 12, borderWidth: 1, borderColor: '#C8D7E2', borderRadius: 8, backgroundColor: C.paper, color: C.ink, fontSize: 13, marginBottom: 10},
  profileShortcut: {minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 9, marginBottom: 10, borderWidth: 1, borderColor: C.line, borderRadius: 9, backgroundColor: C.paper},
  profileShortcutIcon: {width: 38, height: 38, borderRadius: 11, overflow: 'hidden'},
  profileShortcutTitle: {fontSize: 12, fontWeight: '800', color: C.ink},
  profileShortcutSub: {fontSize: 10, color: C.muted, marginTop: 3},
  severityLegend: {flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10},
  severityLegendItem: {width: '48%', minHeight: 45, padding: 8, borderRadius: 7, justifyContent: 'center'},
  severityLegendName: {fontSize: 10, color: C.ink, fontWeight: '800'},
  severityLegendRange: {fontSize: 9, color: C.muted, marginTop: 2},
  severityMild: {backgroundColor: '#EAF2FC'},
  severityModerate: {backgroundColor: '#FFF7D8'},
  severitySevere: {backgroundColor: '#FFF0DC'},
  severityCritical: {backgroundColor: '#FDE7E8'},
  filterChipRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 9},
  filterChip: {minHeight: 32, paddingHorizontal: 11, borderRadius: 18, borderWidth: 1, borderColor: '#B9CBD9', backgroundColor: C.paper, alignItems: 'center', justifyContent: 'center'},
  filterChipActive: {backgroundColor: C.green, borderColor: C.green},
  filterChipText: {fontSize: 10, fontWeight: '700', color: C.blue},
  filterChipTextActive: {color: C.paper},
  reportAddressCard: {padding: 10, marginTop: 9, borderRadius: 7, borderWidth: 1, borderColor: '#C8D7E2', backgroundColor: '#F5F8FA'},
  reportAddressTitle: {fontSize: 10, color: C.blue, fontWeight: '800'},
  reportAddressText: {fontSize: 12, color: C.ink, marginTop: 4},
  requiredHint: {fontSize: 9, color: C.muted, fontWeight: '500'},
  severityChoices: {flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 9},
  severityChoice: {width: '48%', minHeight: 52, padding: 8, borderRadius: 7, borderWidth: 1, borderColor: 'transparent'},
  severityChoiceActive: {borderColor: C.blue, borderWidth: 2},
  severityChoiceLabel: {fontSize: 11, fontWeight: '800', color: C.ink},
  severityChoiceRange: {fontSize: 9, color: C.muted, marginTop: 3},
  photoGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10},
  photoTile: {width: 82, alignItems: 'center', position: 'relative'},
  photoThumbnail: {width: 76, height: 66, borderRadius: 7, backgroundColor: C.paleBlue},
  photoTileCaption: {fontSize: 9, color: C.muted, marginTop: 3, maxWidth: 76},
  photoRemove: {position: 'absolute', top: -5, right: 0, width: 21, height: 21, borderRadius: 11, backgroundColor: C.red, alignItems: 'center', justifyContent: 'center'},
  photoRemoveText: {fontSize: 16, lineHeight: 18, color: C.paper, fontWeight: '700'},
  readOnlyFieldLabel: {fontSize: 10, color: C.blue, fontWeight: '700', marginTop: 10},
  readOnlyField: {minHeight: 42, justifyContent: 'center', paddingHorizontal: 11, paddingVertical: 10, borderWidth: 1, borderColor: '#C9D6E0', borderRadius: 6, backgroundColor: '#F5F8FA', color: C.muted, fontSize: 13, marginTop: 4},
  profileLocationNote: {flexDirection: 'row', gap: 8, padding: 10, borderRadius: 7, backgroundColor: '#E5F7EB', marginTop: 8},
  profileLocationIcon: {fontSize: 16, color: C.green, fontWeight: '800'},
  profileLocationText: {flex: 1, fontSize: 10, color: '#31664A', lineHeight: 15},
  linkButton: {alignItems: 'center', paddingTop: 16, paddingBottom: 2},
  linkText: {color: C.blue, fontWeight: '800', fontSize: 12},
  disabledText: {opacity: 0.45},
  fieldWrap: {marginTop: 11, flex: 1},
  fieldRow: {flexDirection: 'row', gap: 10},
  fieldGrow: {flex: 1},
  fieldNarrow: {width: 122},
  inputLabel: {fontSize: 12, fontWeight: '700', color: C.ink, marginBottom: 6},
  input: {minHeight: 44, paddingHorizontal: 11, paddingVertical: 9, borderWidth: 1, borderColor: '#C9D6E0', borderRadius: 6, backgroundColor: '#FFFFFF', color: C.ink, fontSize: 14},
  multilineInput: {minHeight: 104, lineHeight: 20},
  choiceRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 3, marginBottom: 3},
  choice: {minHeight: 42, paddingHorizontal: 10, borderWidth: 1, borderColor: '#D7E0EC', borderRadius: 10, alignItems: 'center', flexDirection: 'row', gap: 7, backgroundColor: C.paper, flexGrow: 1},
  choiceCompact: {minHeight: 38, paddingHorizontal: 9, flexGrow: 0},
  choiceActive: {borderColor: C.blue, backgroundColor: C.paleBlue},
  choiceText: {fontSize: 11, color: C.muted, fontWeight: '600'},
  choiceTextActive: {color: C.blue, fontWeight: '800'},
  radio: {width: 15, height: 15, borderRadius: 8, borderWidth: 1.5, borderColor: '#AAB6C8', alignItems: 'center', justifyContent: 'center'},
  radioActive: {borderColor: C.blue},
  radioInner: {width: 7, height: 7, borderRadius: 4, backgroundColor: C.blue},
  helperText: {fontSize: 11, color: '#8290A5', lineHeight: 16, marginTop: 5},
  toggleLine: {flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 12, borderBottomColor: '#EDF0F5', borderBottomWidth: 1},
  toggleTitle: {fontSize: 12, fontWeight: '700', color: C.ink, lineHeight: 17},
  notice: {borderWidth: 1, borderRadius: 11, paddingVertical: 10, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginVertical: 7},
  noticeInfo: {backgroundColor: C.paleBlue, borderColor: '#C8D8FF', color: C.blue},
  noticeError: {backgroundColor: C.redSoft, borderColor: '#EBC6C8', color: C.red},
  noticeSuccess: {backgroundColor: C.greenSoft, borderColor: '#C8E7D1', color: C.green},
  noticeSymbol: {fontSize: 13, fontWeight: '900'},
  noticeText: {fontSize: 11, lineHeight: 16, flex: 1},
  privacyNote: {flexDirection: 'row', gap: 8, alignItems: 'flex-start', padding: 12, borderRadius: 12, backgroundColor: '#EEF3FE', marginVertical: 5},
  privacyIcon: {textAlign: 'center', width: 17, height: 17, borderRadius: 9, color: C.blue, backgroundColor: '#DBE7FF', fontSize: 11, fontWeight: '900', overflow: 'hidden'},
  privacyText: {fontSize: 11, lineHeight: 16, color: '#52678A', flex: 1},
  emptyState: {alignItems: 'center', paddingVertical: 17, paddingHorizontal: 9},
  emptyIcon: {width: 42, height: 42, borderRadius: 14, backgroundColor: C.paleBlue, alignItems: 'center', justifyContent: 'center', marginBottom: 9},
  emptyIconText: {color: C.blue, fontSize: 22, fontWeight: '700'},
  emptyTitle: {fontSize: 14, fontWeight: '800', color: C.ink, textAlign: 'center'},
  emptyDescription: {fontSize: 12, color: C.muted, lineHeight: 18, textAlign: 'center', marginTop: 5, maxWidth: 300},
  farmRow: {flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, borderBottomColor: '#EDF0F5', borderBottomWidth: 1},
  farmRowSelected: {backgroundColor: '#F8FAFF', marginHorizontal: -7, paddingHorizontal: 7, borderRadius: 10},
  farmPin: {width: 34, height: 34, borderRadius: 11, backgroundColor: C.greenSoft, alignItems: 'center', justifyContent: 'center'},
  farmPinText: {fontSize: 17, color: C.green, fontWeight: '800'},
  farmName: {fontSize: 13, fontWeight: '800', color: C.ink},
  farmAddress: {fontSize: 10, color: C.muted, lineHeight: 15, marginTop: 3},
  farmMeta: {alignItems: 'flex-end'},
  farmArea: {fontSize: 10, fontWeight: '700', color: C.ink},
  farmPinStatus: {fontSize: 9, color: C.muted, marginTop: 4},
  propertyOption: {flexDirection: 'row', alignItems: 'center', gap: 9, padding: 11, borderWidth: 1, borderColor: C.line, borderRadius: 11, marginTop: 7},
  propertyOptionActive: {borderColor: C.blue, backgroundColor: C.paleBlue},
  propertyOptionTitle: {fontSize: 12, fontWeight: '800', color: C.ink},
  propertyOptionSub: {fontSize: 10, color: C.muted, marginTop: 3},
  photoActions: {flexDirection: 'row', gap: 8},
  photoRow: {flexDirection: 'row', alignItems: 'center', gap: 9, borderTopColor: '#EDF0F5', borderTopWidth: 1, marginTop: 9, paddingTop: 9},
  photoName: {flex: 1, color: C.ink, fontSize: 11},
  removeText: {color: C.red, fontSize: 11, fontWeight: '700'},
  formFooter: {textAlign: 'center', fontSize: 10, color: C.muted, marginTop: 8},
  mapCard: {padding: 0, overflow: 'hidden'},
  coverageRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderTopColor: '#EDF0F5', borderTopWidth: 1},
  coverageArea: {fontSize: 12, color: C.ink, fontWeight: '700', flex: 1},
  mapWebView: {height: 360, backgroundColor: '#eaf0ea'},
  mapOffline: {height: 240, alignItems: 'center', justifyContent: 'center', padding: 25, backgroundColor: '#EAF0EA'},
  mapOfflineIcon: {fontSize: 35, color: C.green, marginBottom: 8},
  mapAttribution: {textAlign: 'right', fontSize: 10, color: C.muted, marginTop: -5, marginBottom: 7},
  coordinatesText: {fontSize: 10, color: C.muted, marginTop: 6},
  authMapPreview: {height: 150, borderRadius: 8, marginTop: 10, overflow: 'hidden'},
  reportRow: {flexDirection: 'row', alignItems: 'center', gap: 9, padding: 9, marginTop: 7, borderColor: '#D8E3EB', borderWidth: 1, borderRadius: 8, backgroundColor: C.paper},
  detailStatus: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 5},
  detailLabel: {marginTop: 16},
  reportRowIcon: {width: 34, height: 34, borderRadius: 11, backgroundColor: C.paleBlue, alignItems: 'center', justifyContent: 'center'},
  reportRowIconText: {fontSize: 16, color: C.blue, fontWeight: '800'},
  reportRowName: {fontSize: 12, fontWeight: '800', color: C.ink},
  reportRowMeta: {fontSize: 10, color: C.muted, marginTop: 3},
  reportRowSub: {fontSize: 10, color: '#8692A5', marginTop: 2},
  queueError: {fontSize: 10, color: C.red, marginTop: 3},
  pill: {alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, backgroundColor: C.paleBlue},
  pillBlue: {backgroundColor: C.paleBlue, color: C.blue},
  pillGreen: {backgroundColor: C.greenSoft, color: C.green},
  pillAmber: {backgroundColor: C.amberSoft, color: C.amber},
  pillRed: {backgroundColor: C.redSoft, color: C.red},
  pillGray: {backgroundColor: '#EEF1F5', color: C.muted},
  pillText: {fontSize: 9, fontWeight: '800'},
  communityCard: {borderTopColor: '#EDF0F5', borderTopWidth: 1, paddingTop: 13, marginTop: 12},
  communityHeader: {flexDirection: 'row', alignItems: 'center', gap: 8},
  communityDate: {fontSize: 10, color: C.muted, flex: 1},
  communityTitle: {fontSize: 14, color: C.ink, fontWeight: '800', lineHeight: 20, marginTop: 11},
  communityFoot: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, marginBottom: 3},
  communityStatus: {fontSize: 10, color: C.muted},
  profileHeader: {flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 13},
  profileName: {fontSize: 16, fontWeight: '800', color: C.ink},
  avatar: {width: 48, height: 48, borderRadius: 17, backgroundColor: C.greenSoft, justifyContent: 'center', alignItems: 'center'},
  avatarText: {fontSize: 20, fontWeight: '900', color: C.green},
  infoRow: {flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 12, borderTopColor: '#EDF0F5', borderTopWidth: 1},
  infoRowCompact: {alignItems: 'flex-start'},
  infoLabel: {fontSize: 11, color: C.muted},
  infoValue: {fontSize: 11, color: C.ink, fontWeight: '700', textAlign: 'right', flexShrink: 1},
  bottomNav: {height: 68, paddingHorizontal: 5, paddingBottom: Platform.OS === 'ios' ? 4 : 2, backgroundColor: C.paper, borderTopColor: C.line, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around'},
  navButton: {flex: 1, height: 60, alignItems: 'center', justifyContent: 'center', gap: 2},
  navIconWrap: {minWidth: 38, height: 29, borderRadius: 10, alignItems: 'center', justifyContent: 'center'},
  navIconWrapActive: {backgroundColor: C.greenSoft},
  navIconText: {fontSize: 20, color: '#8290A5', fontWeight: '700'},
  navIconTextActive: {color: C.green},
  navLabel: {fontSize: 9, color: '#7B889C', fontWeight: '600'},
  navLabelActive: {color: C.green, fontWeight: '800'},
  navBadge: {position: 'absolute', top: -3, right: -3, minWidth: 14, height: 14, borderRadius: 7, backgroundColor: C.amber, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 3},
  navBadgeText: {fontSize: 8, color: C.paper, fontWeight: '900'},
  primaryNavAction: {width: 61, height: 58, alignItems: 'center', justifyContent: 'center', marginTop: -12},
  primaryNavPlus: {backgroundColor: C.green, color: C.paper, width: 36, height: 36, textAlign: 'center', textAlignVertical: 'center', fontSize: 23, fontWeight: '600', borderRadius: 18, overflow: 'hidden'},
  primaryNavLabel: {fontSize: 9, color: C.green, fontWeight: '800', marginTop: 2},
  loadingRoot: {flex: 1, backgroundColor: C.background, justifyContent: 'center', alignItems: 'center'},
  loadingText: {fontSize: 13, color: C.muted, marginTop: 11},
});

export {C, styles};
